<?php


class ClienteTest extends TestCase
{
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->cliente = new Cliente;
    }

    public function testClasse()
    {
        $this->assertInstanceOf('Cliente', $this->cliente);
    }

    public function testConsumidores()
    {
//        $environment = App::environment();
//        var_dump($environment);die;
        $ret = $this->cliente->find(1)->consumidores->find(1);
        $this->assertEquals('Nome-1', $ret->nome);

    }

    /**
     * @return \Illuminate\Foundation\Application
     */
    public function testEndereco()
    {
        $ret = $this->cliente->find(1)->endereco;
        $this->assertEquals('rua Doze de Outubro', $ret->logradouro);
    }

    public function testItens()
    {
        $ret = $this->cliente->find(1)->itens->find(1);
        $this->assertEquals('Nome do Produto 1', $ret->nome);
    }
}
