<?php


class ClienteEnderecoTest extends TestCase
{

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->endereco = new ClienteEndereco;
    }

    public function testClasse()
    {
        $this->assertInstanceOf('ClienteEndereco', $this->endereco);
    }
}
