<?php


class ConsumidorTest extends TestCase
{
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->consumidor = new Consumidor;
    }

    public function testClasse()
    {
        $this->assertInstanceOf('Consumidor', $this->consumidor);
    }

    public function testConsumidor()
    {
        $ret = $this->consumidor->find(1);

        $this->assertEquals('Nome-1', $ret->nome);
    }

    public function testEndereco()
    {
        $ret = $this->consumidor->find(1)->endereco;

        $this->assertEquals('Endereco-1', $ret->logradouro);

    }

    public function testPedidos()
    {
        $ret = $this->consumidor->find(1)->pedidos->find(1);
        $this->assertEquals('73.05', $ret->valor_total);
    }
}
